AWSTemplateFormatVersion: '2010-09-09'
Resources:
  LambdaExecutionRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: 'Allow'
            Principal:
              Service: 'lambda.amazonaws.com'
            Action: 'sts:AssumeRole'
      Policies:
        - PolicyName: 'LambdaExecutionPolicy'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: 'Allow'
                Action: 
                  - 'logs:*'
                  - 'dynamodb:*'
                Resource: '*'
  BidAdjusterFunction:
    Type: 'AWS::Lambda::Function'
    Properties:
      FunctionName: 'BidAdjusterFunction'
      Handler: 'src/lambda_function.lambda_handler'
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        S3Bucket: 'your-bucket-name'
        S3Key: 'bid_adjuster.zip'
      Runtime: 'python3.8'
      Timeout: 60
      MemorySize: 128
